package com.example.project_b1_test.db;

public class QandA2 {

    public static String Question[] = {
            "I need to get some cash. Do you think we might pass a bank ______?",
            "Will you ______ the children while I’m out?",
            "I liked the coat when I bought it , but now I’ve ______ my mind.",
            "In the middle of all the panic, she ______ phoned the police.",
            "The boy’s mother was ______ in by his lies.",
            "I find her ______ she never stops talking.",
            "I often wonder what people abroad make ______ Britain.",
            "There are about twenty ______ people waiting in the outer office.",
            "The Comanche are largely of mixed blood India and Spanish (descent).",
            "Many people consider automobiles to be (essential) to American life.",
            "Some species of birds, when migrating divide (according to) their age and sex.",
            "Writing is a skill that requires (consistent) practice.",
            "The traffic in town was very ______ and I arrived home earlier than expected.",
            "In all parts of the U.S there is (adequate) rainfall except near the Rock Mountains.",
            "City governments are (belatedly) taking steps to revitalize downtown areas.",
            "Aerobic bacteria transforms wastes in water into less (dangerous) substances.",
            "The evidence that carbon dioxide levels are rising is ______.",
            "I don’t agree with you, but your idea certainly gives me food ______.",
            "He opened the letter without ______ to read the address on the envelope",
            "Do you have any objections ______ this new road scheme?",
            "The police set a ______ to catch the thieves.",
            "Although he was ______, he agreed to play tennis with me.",
            "______ I didn’t know how to do the job. But now I am making progress",
            "Language could ______ more quickly if there were more language exchange programs.",
            "She won the award for ______ her whole life to looking after the poor."
    };

    public static String Answer[][] = {
            {"A. in the way","B. to the way","C. on the way","D. at the way"},
            {"A. pay attention to", "B. care about","C. look after", "D. look out"},
            {"A. altered","B. decided","C. reversed","D. changed"},
            {"A. silently" ,"B. calmly","C. peacefully","D. middy"},
            {"A. drawn","B. taken","C. pulled","D. caught"},
            {"A. exhaustion","exhaustion","B. exhaust","C. exhausting","D. exhausted"},
            {"A. from" ,"B. of","C. for","D. by"},
            {"A. but","B. and","C. for","D. or"},
            {"A. pedigree","B. origin","C. race","D. birth"},
            {"A. critical","B. accessible","C. necessary","D. advantageous"},
            {"A. in keeping with","B. conforming to","C. in line with","D. in relation to"},
            {"A. invariable","B. orderly","C. regular","D. customary"},
            {"A. light","B. weak","C. little","D. few"},
            {"A. sufficient","B. acceptable","C. abundant","D. suitable"},
            {"A. Endlessly","B. impatiently","C. finally","D. recently"},
            {"A. Stable","B. precarious","C. tender","D. harmless"},
            {"A. inevitable","B. unavoidable","C. undeniable","D. indelible"},
            {"A. For fun","B. for consider","C. for thought","D. for thinking"},
            {"A. worrying","B. bothering","C. fearing","D. caring"},
            {"A. at", "B. with", "C. to", "D. for"},
            {"A. plan" , "B. device" , "C. snare", "D. trap"},
            {"A. exhaustion", "B. exhausted", "C. exhausting", "D. exhaustive"},
            {"A. First", "B. First of all", "C. At first", "D. At the first."},
            {"A. be learning", "B. have learned", "C. have learning", "D. be learned"},
            {"A. paying", "B. devoting", "C. causing", "D. attracting"}
    };

    public static String correctAnswer[] = {
            "C. on the way",
            "C. look after",
            "A. altered",
            "B. calmly",
            "B. taken",
            "C. exhausting",
            "B. of",
            "D. or",
            "B. origin",
            "C. necessary",
            "C. in line with",
            "C. regular",
            "A. light",
            "A. sufficient",
            "C. finally",
            "B. precarious",
            "C. undeniable",
            "C. for thought",
            "B. bothering",
            "C. to",
            "D. trap",
            "B. exhausted",
            "C. At first",
            "D. be learned",
            "B. devoting"
    };
}
